version: '3'
services:
  metering:
    image: $REPOSITORY/metering-service:$ODMVERSION
    build:
        context: ./
        dockerfile: ./${ODMDOCKERDIR}/Dockerfile
        args:
          - ODMDOCKERDIR=$ODMDOCKERDIR
          - ODMVERSION=$ODMVERSION
          - FROMLIBERTY=$FROMLIBERTY
          - FROMLIBERTYBUILD=$FROMLIBERTY
    ports:
    - 8888:8888


