secrets:
  artifactory_user:
    environment: ARTIFACTORY_USER
  artifactory_token:
    environment: ARTIFACTORY_TOKEN
services:
  metering:
    image: $REPOSITORY/metering-service:$ODMIMAGEVERSION
    build:
        context: ./
        dockerfile: ./${ODMDOCKERDIR}/Dockerfile
        args:
          - ODMDOCKERDIR=$ODMDOCKERDIR
          - ODMVERSION=$ODMIMAGEVERSION
          - FROMLIBERTY=$FROMLIBERTY
          - FROMLIBERTYBUILD=$FROMLIBERTY
        secrets:
          - artifactory_user
          - artifactory_token
#    volumes:
#      - ./metering-options:/config/bootstrap.properties
#      - ./docker/certificate/keystore.jks:/config/resources/certificate/keystore.jks
    ports:
    - 8888:8888
    - 9999:9999



