version: '3'
services:
  metering-service:
    image: myrepo/metering-service:8.10.5.0-amd64
    ports:
    - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://metering-service:8888"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - METERING_LOGGINGLEVEL=DEBUG
      - METERING_PROCESSINGRATE=6000
      - METERING_PROCESSING_INITIAL_DELAY=6000
  

  dbserver:
    image: $REPOSITORY/dbserver:$ODMVERSION

    ports:
    - 5432:5432
    environment:
      - POSTGRESQL_USER=odmusr
      - POSTGRESQL_PASSWORD=odmpwd
      - POSTGRESQ_DB=odmdb
      - PGDATA=/var/lib/postgresql/data
      - SAMPLE=true
# Uncomment this line to persist your data. Note that on OSX you need to share this
# current directory in the Preference menu -> File Sharing menu.
#    volumes:
#      - ./pgdata:/pgdata

  odm-decisionserverconsole:
    image: $REPOSITORY/odm-decisionserverconsole:$ODMVERSION
    environment:
      - POSTGRESQL_USER=odmusr
      - POSTGRESQL_PASSWORD=odmpwd
      - POSTGRESQ_DB=odmdb
      - PGDATA=/var/lib/postgresql/data
      - SAMPLE=true
      - COM_IBM_RULES_METERING_ENABLE=TRUE
    links:
    - dbserver
    depends_on:
    - dbserver
    ports:
    - 9080:9080
    - 1883:1883
    - 9843:9443
    volumes:
    - ./plugin-configuration.properties:/config/baiemitterconfig/plugin-configuration.properties

  