apiVersion: v1
entries:
  ibm-odm-metering:
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2021-03-24T17:50:55.684662+01:00"
    description: IBM Operational Decision Manager metering service
    digest: bdbaab5f19a12602390b43076fa605b71e7b2ba990f480d31d90a3f9fa031b0e
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://odmdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2021-03-24T17:50:55.686929+01:00"
    description: IBM Operational Decision Manager metering service
    digest: dcc72553b276a619cc59ccc75e923e9a97e76ef2595cbf381431100c0ced9c00
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://odmdev.github.io/decisions-metering/charts/stable/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
generated: "2021-03-24T17:50:55.681947+01:00"
