apiVersion: v1
entries:
  ibm-odm-metering:
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2021-03-24T16:36:37.387422+01:00"
    description: IBM Operational Decision Manager metering service
    digest: 1966efdf26a639bed90c3acb819ab09495fde057cca2dc8641ef140fa156d272
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    urls:
    - https://odmdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2021-03-24T16:36:37.389136+01:00"
    description: IBM Operational Decision Manager metering service
    digest: a681ee151772ef3917a836277ef1ee7fa97f3f9437566059b364875cfb6468fb
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    urls:
    - https://odmdev.github.io/decisions-metering/charts/stable/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
generated: "2021-03-24T16:36:37.385545+01:00"
