apiVersion: v1
entries:
  ibm-odm-dev:
  - apiVersion: v2
    appVersion: 8.11.1.0
    created: "2022-12-19T09:00:37.096570825Z"
    description: 'IBM Operational Decision Manager for Developers    License   By
      installing this product you accept the following license terms: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-ASAY-CE4DNS'
    digest: 6eec78dd74b4019edd46cf8af95498e667d696c7a67002dfc8334a00b1b7c41b
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - RHOCP
    - ROKS
    - Middleware
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: IBM
    name: ibm-odm-dev
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    urls:
    - https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-odm-dev-22.2.0.tgz
    version: 22.2.0
  ibm-odm-prod:
  - apiVersion: v2
    appVersion: 8.11.1.0
    created: "2022-12-16T00:23:48.568548799Z"
    description: 'IBM Operational Decision Manager  License By installing this product
      you accept the following license terms: https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-ASAY-C55D8E'
    digest: 7199d9b2379312a09dc2b954fd554fc7c50c3764c0af923971eea56a6274f716
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Commercial
    - s390x
    - ppc64le
    - amd64
    - ICP
    - RHOCP
    - Middleware
    kubeVersion: '>=1.11.0-0'
    maintainers:
    - name: IBM
    name: ibm-odm-prod
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    urls:
    - https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-odm-prod-22.2.0.tgz
    version: 22.2.0
  ibm-odm-metering:
  - apiVersion: v1
    appVersion: 8.11.1.0
    created: "2022-12-12T16:03:23.836924+01:00"
    description: IBM Operational Decision Manager metering service
    digest: a8a0395cd1aec92450d2aa30530a17018227b7508a562c1c6f0cec3fc500559b
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0-0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-22.2.0.tgz
    version: 22.2.0
  - apiVersion: v1
    appVersion: 8.11.0.1
    created: "2022-12-12T16:03:23.835322+01:00"
    description: IBM Operational Decision Manager metering service
    digest: 2c33beb49aab6f029a07189eb8df9b21cc654a54f0d93a06aed92c89c0ebfe4b
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0-0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-22.1.0.tgz
    version: 22.1.0
  - apiVersion: v1
    appVersion: 8.11.0.0
    created: "2022-12-12T16:03:23.832498+01:00"
    description: IBM Operational Decision Manager metering service
    digest: c201c12f38caeee07efb38c37a06ed4d3cae3568b2ca2ed8cdf4533aa9e084a7
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0-0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.3.0.tgz
    version: 21.3.0
  - apiVersion: v1
    appVersion: 8.10.5.1
    created: "2022-12-12T16:03:23.828257+01:00"
    description: IBM Operational Decision Manager metering service
    digest: 9c46e4f530627859510695a5174bc5bbd4cee617d0b77e2ff672ac95e7d67b00
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.2.0.tgz
    version: 21.2.0
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2022-12-12T16:03:23.82512+01:00"
    description: IBM Operational Decision Manager metering service
    digest: 1b05aadbc86ba87d653a7d750a5243891039dbf876088a91b5d961a4ec524186
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
generated: "2022-12-12T16:03:23.819108+01:00"
