apiVersion: v1
entries:
  ibm-odm-metering:
  - apiVersion: v1
    appVersion: 8.10.5.0
    created: "2021-04-26T14:52:27.333508+02:00"
    description: IBM Operational Decision Manager metering service
    digest: 1b05aadbc86ba87d653a7d750a5243891039dbf876088a91b5d961a4ec524186
    home: https://developer.ibm.com/odm/
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - ICP
    - amd64
    - s390x
    - ppc64le
    - ICPRHOCP
    kubeVersion: '>=1.11.0'
    maintainers:
    - name: ODMDev
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://odmdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-21.1.0.tgz
    version: 21.1.0
generated: "2021-04-26T14:52:27.327719+02:00"
