apiVersion: v1
entries:
  ibm-odm-metering:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-27T16:24:17.702275+02:00"
    description: 'IBM Operational Decision Manager for Developers    License   By
      installing this product you accept the following license terms: https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-DHWR-YJBM3D'
    digest: 06d64eb890baaf177f27d866542a8a48af5bd6ae0fea9bf742df1fb21b74b7af
    home: https://www.ibm.com/docs/en/odm/9.6.0
    icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
    keywords:
    - OperationalDecisionManager
    - businessrules
    - Limited
    - RHOCP
    - ROKS
    - amd64
    - s390x
    - ppc64le
    - Middleware
    kubeVersion: '>= 1.25.0-0'
    maintainers:
    - name: ODMDev
    - name: IBM
    name: ibm-odm-metering
    sources:
    - https://github.com/ODMDev/decisions-metering
    urls:
    - https://decisionsdev.github.io/decisions-metering/charts/stable/ibm-odm-metering-1.0.0.tgz
    version: 1.0.0
generated: "2026-05-27T16:24:17.701381+02:00"
